In [2]:
from __future__ import division
import numpy as np
import math

In [3]:
def signature_bit(data, planes):
    sign = []
    for p in planes:
        if(len(data) != len(p)):
            return None
        if np.dot(data, p) >= 0:
            sign.append(1)
        else:
            sign.append(0)

    return sign

In [4]:
def cosineValues(images, signatureSize):

    dim = len(images[0])  # dimension of data points (# of features)
    signatures = []
    #reference planes
    ref_planes = np.random.randn(signatureSize, dim)

    for i in range(len(images)):
        point = images[i]
        sig1 = signature_bit(point, ref_planes)
        if sig1 != None:
            signatures.append(sig1)
    return np.array(signatures)

In [8]:
T = [[3, 0, 0, 0, 0], [0, 4, 0, 0, 0], [0, 0, 0, 0, 0], [3, 5, 7, 12, 1]]
c = np.array([[1,5,70],[20,3,7],[3000,1100,-6000], [3,11,12]])
x = cosineValues(c, 16)
print(x)
x.shape

[[0 0 0 1 0 1 0 0 1 0 0 0 1 0 0 1]
 [1 0 1 1 0 1 1 1 1 0 1 0 0 0 1 0]
 [1 1 1 0 1 1 1 1 1 0 1 1 0 1 1 0]
 [1 0 1 1 1 1 0 0 1 0 1 0 1 0 0 0]]


(4, 16)